# Generated by Django 5.0.2 on 2024-03-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornaliero',
            name='differenza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='giornaliero',
            name='incassoPresunto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='giornaliero',
            name='totaleCassa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
