# Generated by Django 5.0.2 on 2024-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiche', '0003_alter_giornaliero_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='descMovimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
