# Generated by Django 5.0.2 on 2024-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiche', '0004_descmovimenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettagli',
            name='movimento',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
