# Generated by Django 5.0.2 on 2024-03-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiche', '0005_alter_dettagli_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='descmovimenti',
            name='descrizione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dettagli',
            name='movimento',
            field=models.CharField(choices=[('TABACCHI', 'TABACCHI'), ('LOTTO', 'LOTTO'), ('ART. TABACCHERIA', 'ART. TABACCHERIA'), ('SISAL', 'SISAL'), ('GRATTA E VINCI', 'GRATTA E VINCI'), ('ALTRE USCITE', 'ALTRE USCITE'), ('PASTIGLIAGGI', 'PASTIGLIAGGI'), ('VALORI BOLLATI', 'VALORI BOLLATI')], max_length=100),
        ),
    ]
