# Generated by Django 5.0.2 on 2024-03-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiche', '0006_descmovimenti_descrizione_alter_dettagli_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettagli',
            name='movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistiche.descmovimenti'),
        ),
    ]
